language: node_js
node_js:
    - "0.10"
services:
    - xvfb
before_install:
    - export CHROME_BIN=chromium-browser
before_script:
    - npm install
script: 
    - npm install
    - node_modules/karma/bin/karma start karma.conf.js --single-run